name: find_room
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: 0.12.9+2
  firebase_auth: ^0.14.0+2
  firebase_storage: ^3.0.5
  image_picker: ^0.6.1+3
  json_serializable: ^3.2.0 #flutter packages pub run build_runner build
  distinct_value_connectable_observable: ^2.0.2
  rxdart: ^0.22.1+1
  shared_preferences: ^0.5.3+4
  flutter_swiper: ^1.1.6
  intl: ^0.15.8
  tuple: ^1.0.2
  collection: ^1.14.11
  cached_network_image: ^1.1.1
  wave: ^0.0.8
  google_sign_in: ^4.0.6
  flutter_facebook_login: ^2.0.1
  path: ^1.6.2
  built_value: ^6.7.0
  sealed_unions: ^3.0.2+2
  disposebag: ^1.0.0
  url_launcher: ^5.1.2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.6
  built_value_generator: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/home_appbar_image.jpg
  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.ttf
        - asset: assets/fonts/SF-Pro-Text-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.ttf
          weight: 700
